[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Analysis Utils"
authors = [{name = "A.I.H.", email = "no"}]
dynamic = ["version", "description"]
